### ISSUE TITLE
unable to compile: use of undeclared identifier 'test_arrival_time_uncertainty'

### ISSUE THREAD

**Issue by mef51** [rossjjennings/psrchive#1]
Hi I was unable to compile psrchive due to the following error:

```
pat.C:522:5: error: use of undeclared identifier 'test_arrival_time_uncertainty'
    test_arrival_time_uncertainty (ntest_uncertainty, stdarch, arrival);
    ^
1 error generated.
make[4]: *** [pat.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I dug into it a big and I believe the issue has to do with these commits that added that function: 
https://github.com/rossjjennings/psrchive/commit/0737cad2c117df62dd638c3f8e822ae5c5504803
https://github.com/rossjjennings/psrchive/commit/a3744448ff3a2bdadb82429d5494f39f134f572a

I tried to move the implementation for `test_arrival_time_uncertainty` from its file into pat.C but that didn't work.
My workaround was to comment out the one call to it in pat.C [(Line 513)](https://github.com/rossjjennings/psrchive/blob/master/More/Applications/pat.C#L513) but of course that probably breaks something. It did finish compiling after that tho

**Comment by rossjjennings** [comment]
Sorry, but I don't think I'll be much help here. This isn't the main PSRCHIVE repo; that's hosted on SourceForge. I just keep this fork here for my own convenience. The real PSRCHIVE maintainer is @straten. He may see this now that I've tagged him, but probably what you really wanted was the PSRCHIVE [Q&A site](https://psrchive.sourceforge.net/qa/) or [bug tracker](https://sourceforge.net/p/psrchive/bugs/).

**Comment by mef51** [comment]
Thanks!

**Comment by straten** [comment]
Thanks for letting me know about the bug.   I think this compilation error arises when PGPLOT is unavailable (I accidentally added the declaration for this function to a block of code preceded by `#if HAVE_PGPLOT` ... I've just checked in a potential fix (at sourceforge)

**Comment by mef51** [comment]
That fixed it! Thank you, I appreciate the quick response
